### ISSUE TITLE
Ambiguous geom type of `kinova_tool.kinbody.xml`

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/pr-ordata#20]
The geom type of [`kinova_tool.kinbody.xml`](https://github.com/personalrobotics/pr-ordata/blob/master/data/objects/kinova_tool.kinbody.xml) is ambiguous. The type value is `sphere` while it contains `<Render>` filed, which is for trimesh type.

I guess the type should be changed to `trimesh`. If someone confirms this, I could make a PR for this.

Related PR: [Aikido #102](https://github.com/personalrobotics/aikido/pull/102)

**Comment by mkoval** [comment]
The current version of the file is correct. See https://github.com/personalrobotics/aikido/pull/102#issuecomment-287583463.
