### ISSUE TITLE
<Data> versus <collision>

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/pr-ordata#21]
It seems the KinBody files in this repo use `<Data>` for collision mesh, but the [spec](http://openrave.programmingvision.com/wiki/index.php/Format:XML) uses `<collision>` instead. Is this intentional or an oversight?

Related PR: [Aikido #102](https://github.com/personalrobotics/aikido/pull/102)

**Comment by jslee02** [comment]
Since `<collision>` is the spec, I would suggest using it rather than `<Data>` unless there is a compelling reason not to do.

**Comment by mkoval** [comment]
This is not ambiguous. See https://github.com/personalrobotics/aikido/pull/102#issuecomment-287583463.

I am fine with switching to `<collision>`. However, I am skeptical of putting too much faith into that specification. In practice, the only thing that matters is what is implemented in the code. 😢
