### ISSUE TITLE
Consider renaming this repo to pr_ordata to match with package name

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/pr-ordata#29]

**Comment by brianhou** [comment]
While we're on the topic of renaming, this repo isn't really for OpenRAVE anymore and could be renamed accordingly.

**Comment by psigen** [comment]
Maybe `pr_models` or `pr_assets`?

**Comment by youngsunkim** [comment]
I renamed this repo to `pr_ordata`. I like `pr_assets` by the way! I will check what we should do for changing the package name to it.

**Comment by jslee02** [comment]
Closing this issue since the repo name is changed. For changing repo name to `pr_assets` or `pr_models`, see #35.
